# Generated by Django 5.1.6 on 2025-03-01 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=6, null=True)),
                ('is_confirmed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topicName', models.CharField(max_length=100)),
                ('dailyPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('weeklyPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monthlyPrice', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('sessionID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('expiry', models.DateTimeField()),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.account')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiry', models.DateTimeField()),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.account')),
                ('topicID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.topic')),
            ],
        ),
        migrations.CreateModel(
            name='TopicVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoName', models.CharField(max_length=200)),
                ('videoLink', models.URLField()),
                ('thumbnail', models.TextField()),
                ('topicID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.topic')),
            ],
        ),
    ]
