# Generated by Django 5.1.6 on 2025-03-18 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_subscription_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='dailyPrice',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='weeklyPrice',
        ),
        migrations.AddField(
            model_name='topic',
            name='quarterlyPrice',
            field=models.IntegerField(default=350000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='topic',
            name='monthlyPrice',
            field=models.IntegerField(),
        ),
    ]
